apiVersion: v1
kind: Namespace
metadata:
  name: ns-httpd
  labels:
    name: ns-httpd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-httpd
  namespace: ns-httpd
spec:
  #eplicas: 2
  selector:
    matchLabels:
      app: app-httpd
  template:
    metadata:
      labels:
        app: app-httpd
    spec:
      containers:
      - name: app-httpd
        image: brunohmg89/httpd-teste:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: app-httpd-service
spec:
    type: NodePort
    selector:
        app: app-httpd
    ports:
        - port: 8080
          targetPort: 8080
