apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-local
  labels:
    type: mypv-local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /meubanco/
