#arquivo será enviado para o Github, porém no ambiente real esse tipo de
#arquivo não pode ser enviado, logo depois de realizar o apply temos que
#apagar o deploy.
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  ROOT_PASSWORD: Senha123
  MYSQL_DATABASE: meubanco
