name: docker-build-dir-ci-cd

on:
  push:
    branches: [main]
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: build-push
      uses: docker/build-push-action@v4.1.1
      with:
        context: ./Code/CI-CD/App/
        tags: brunohmg89/httpd-teste:latest
        push: true
        # dockerfile: ./Code/CI-CD/App/Dockerfile

    - name: use minikube
      uses: medyagh/setup-minikube@master

    - name: kubectl in minikube
      run:
        kubectl get pods -A

    - name: Deploy to minikube
      run: |
          kubectl apply -f Code/CI-CD/Kubernetes/app-httpd.yaml

    - name: kubectl in minikube
      run:
        kubectl get pods      

    - name: Test service URLs
      run: | 
        minikube service list
        minikube service discover --url
        echo -n "------------------opening the service------------------"
        curl $(minikube service discover --url)/version    